//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.widen.product.main;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.FrameLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import com.widen.R.id;
import com.widen.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class OrderDetailAct_
    extends OrderDetailAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String ID_EXTRA = "Id";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.order_detail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static OrderDetailAct_.IntentBuilder_ intent(Context context) {
        return new OrderDetailAct_.IntentBuilder_(context);
    }

    public static OrderDetailAct_.IntentBuilder_ intent(Fragment supportFragment) {
        return new OrderDetailAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        used_item_lay = ((FrameLayout) hasViews.findViewById(id.used_item_lay));
        SettleDay = ((TextView) hasViews.findViewById(id.SettleDay));
        Price = ((TextView) hasViews.findViewById(id.Price));
        Duration = ((TextView) hasViews.findViewById(id.Duration));
        ExpectedPrice = ((TextView) hasViews.findViewById(id.ExpectedPrice));
        Name = ((TextView) hasViews.findViewById(id.Name));
        item_txt = ((TextView) hasViews.findViewById(id.item_txt));
        ExtraInterest = ((TextView) hasViews.findViewById(id.ExtraInterest));
        SellingStatus = ((TextView) hasViews.findViewById(id.SellingStatus));
        ProductIdentifier = ((TextView) hasViews.findViewById(id.ProductIdentifier));
        root_lay = ((ScrollView) hasViews.findViewById(id.root_lay));
        CreatedAt = ((TextView) hasViews.findViewById(id.CreatedAt));
        progressbar = ((ProgressBar) hasViews.findViewById(id.progressbar));
        TotalNumber = ((TextView) hasViews.findViewById(id.TotalNumber));
        OrderNo = ((TextView) hasViews.findViewById(id.OrderNo));
        BankName = ((TextView) hasViews.findViewById(id.BankName));
        no_use_item_lay = ((FrameLayout) hasViews.findViewById(id.no_use_item_lay));
        Yield = ((TextView) hasViews.findViewById(id.Yield));
        {
            View view = hasViews.findViewById(id.back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        OrderDetailAct_.this.back();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.no_use_item_lay);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        OrderDetailAct_.this.no_use_item_lay();
                    }

                }
                );
            }
        }
        afterViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(ID_EXTRA)) {
                Id = extras_.getString(ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, OrderDetailAct_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, OrderDetailAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public OrderDetailAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

        public OrderDetailAct_.IntentBuilder_ Id(String Id) {
            intent_.putExtra(ID_EXTRA, Id);
            return this;
        }

    }

}
