//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.widen.product.main;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.TextView;
import com.widen.R.id;
import com.widen.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ProductDetailAct_
    extends ProductDetailAct
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String ID_EXTRA = "Id";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.product_detail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ProductDetailAct_.IntentBuilder_ intent(Context context) {
        return new ProductDetailAct_.IntentBuilder_(context);
    }

    public static ProductDetailAct_.IntentBuilder_ intent(Fragment supportFragment) {
        return new ProductDetailAct_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        MinNumber = ((TextView) hasViews.findViewById(id.MinNumber));
        Yield = ((TextView) hasViews.findViewById(id.Yield));
        root_lay = ((ScrollView) hasViews.findViewById(id.root_lay));
        seekbar_blue = ((SeekBar) hasViews.findViewById(id.seekbar_blue));
        Unit = ((TextView) hasViews.findViewById(id.Unit));
        progressbar = ((ProgressBar) hasViews.findViewById(id.progressbar));
        ExtraYield = ((TextView) hasViews.findViewById(id.ExtraYield));
        SellingStatus_icon = ((ImageView) hasViews.findViewById(id.SellingStatus_icon));
        PubEnd = ((TextView) hasViews.findViewById(id.PubEnd));
        Unit_txt = ((TextView) hasViews.findViewById(id.Unit_txt));
        number = ((EditText) hasViews.findViewById(id.number));
        SellingStatus = ((TextView) hasViews.findViewById(id.SellingStatus));
        seekbar_red = ((SeekBar) hasViews.findViewById(id.seekbar_red));
        over_lay = ((FrameLayout) hasViews.findViewById(id.over_lay));
        MaxNumber = ((TextView) hasViews.findViewById(id.MaxNumber));
        buy_number_lay = ((FrameLayout) hasViews.findViewById(id.buy_number_lay));
        TotalNumber = ((TextView) hasViews.findViewById(id.TotalNumber));
        Name = ((TextView) hasViews.findViewById(id.Name));
        ProductIdentifier = ((TextView) hasViews.findViewById(id.ProductIdentifier));
        Duration = ((TextView) hasViews.findViewById(id.Duration));
        cat_left_icon = ((ImageView) hasViews.findViewById(id.cat_left_icon));
        flag_icon = ((ImageView) hasViews.findViewById(id.flag_icon));
        SettleDay = ((TextView) hasViews.findViewById(id.SettleDay));
        income = ((TextView) hasViews.findViewById(id.income));
        SellingStatus_txt = ((TextView) hasViews.findViewById(id.SellingStatus_txt));
        yield_star_icon = ((ImageView) hasViews.findViewById(id.yield_star_icon));
        PubBegin = ((TextView) hasViews.findViewById(id.PubBegin));
        {
            View view = hasViews.findViewById(id.howbuy);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProductDetailAct_.this.howbuy();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProductDetailAct_.this.back();
                    }

                }
                );
            }
        }
        afterViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(ID_EXTRA)) {
                Id = extras_.getString(ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ProductDetailAct_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ProductDetailAct_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ProductDetailAct_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

        public ProductDetailAct_.IntentBuilder_ Id(String Id) {
            intent_.putExtra(ID_EXTRA, Id);
            return this;
        }

    }

}
